{ config, pkgs, ... }:

# Git, OpenSSH client and GitHub CLI for the user. This is a Home Manager
# module, it is imported for home-manager.users.femboy in ./flake.nix.

{
  programs.git = {
    enable = true;

    settings = {
      user = {
        name = "hx6h";
        email = "hx6h@proton.me";
      };

      init.defaultBranch = "main";
      pull.rebase = false;

      url."git@github.com:".insteadOf = "https://github.com/";
    };
  };

  programs.ssh = {
    enable = true;

    enableDefaultConfig = false;

    settings = {
      "github.com" = {
        HostName = "github.com";
        IdentityFile = "~/.ssh/id_ed25519";
        User = "git";
      };

      # The "*" block used to be generated by programs.ssh.enableDefaultConfig,
      # which is going away, so the values it produced are spelled out here.
      "*" = {
        AddKeysToAgent = "no";
        Compression = false;
        ControlMaster = "no";
        ControlPath = "~/.ssh/master-%r@%n:%p";
        ControlPersist = "no";
        ForwardAgent = false;
        HashKnownHosts = false;
        ServerAliveCountMax = 3;
        ServerAliveInterval = 0;
        UserKnownHostsFile = "~/.ssh/known_hosts";
      };
    };
  };

  programs.gh = {
    enable = true;
    settings.git_protocol = "ssh";
  };
}
