wallpaper {
    monitor = HDMI-A-1
    path = /home/femboy/.config/images/wall3.png
    fit_mode = stretch
}

wallpaper {
    monitor = eDP-1
    path = /home/femboy/.config/images/wall3.png
    fit_mode = stretch
}

splash = false
